# -*- coding: utf-8 -*-
"""collabarative.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11WRlg3oV6CnePCgP2VNW2lqeamd8mmte
"""

import pandas as pd

import numpy as np

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.metrics.pairwise import cosine_similarity

def get_title_from_index(index):
	return df[df.index == index]["title"].values[0]

def get_index_from_title(title):
	return df[df.title == title]["index"].values[0]



df=pd.read_csv('movie_dataset.csv')

df.head()

df['original_title'].head()

sort_rating=sorted(df['vote_average'],reverse=True)

sort_rating[2]

cnt=0
for i in sort_rating:
  if i>7:
    cnt+=1
print(cnt)

df_sorted=df.sort_values('popularity',ascending=False)

df_sorted.head()

pop_movies=df_sorted[df_sorted['popularity']>50]

pop_movies.count

random=np.random.choice(pop_movies['index'],20)

random

d={}
for index in random:
  d[index]=get_title_from_index(index)
  
print(d)

